CREATE TABLE USERS
(
  ID       INT          NOT NULL             GENERATED ALWAYS AS IDENTITY,
  CREATED  TIMESTAMP    NOT NULL             DEFAULT CURRENT_TIMESTAMP,
  MODIFIED TIMESTAMP                         DEFAULT CURRENT_TIMESTAMP,
  LOGIN    VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CONSTRAINT users_id_primary_key PRIMARY KEY (ID),
  CONSTRAINT users_login_unique UNIQUE (LOGIN)
);

CREATE TABLE CATEGORIES
(
  ID   INT          NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(255) NOT NULL,
  CONSTRAINT categories_id_primary_key PRIMARY KEY (ID),
  CONSTRAINT categories_name_unique UNIQUE (NAME)
);

CREATE TABLE TEMPLATES
(
  ID           INT          NOT NULL             GENERATED ALWAYS AS IDENTITY,
  PARENT_ID    INT,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(255),
  ORDER_NUMBER INT          NOT NULL,
  CATEGORY_ID  INT,
  CREATED      TIMESTAMP    NOT NULL             DEFAULT CURRENT_TIMESTAMP,
  MODIFIED     TIMESTAMP                         DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT templates_id_primary_key PRIMARY KEY (ID),
  CONSTRAINT templates_parent_id_foreign_key FOREIGN KEY (PARENT_ID)
  REFERENCES TEMPLATES (ID),
  CONSTRAINT templates_category_id_foreign_key FOREIGN KEY (CATEGORY_ID)
  REFERENCES CATEGORIES (ID)
);

CREATE TABLE TASKS
(
  ID           INT          NOT NULL             GENERATED ALWAYS AS IDENTITY,
  PARENT_ID    INT,
  NAME         VARCHAR(255) NOT NULL,
  DESCRIPTION  VARCHAR(255),
  ORDER_NUMBER INT          NOT NULL,
  STATUS       BOOLEAN      NOT NULL             DEFAULT FALSE,
  USER_ID      INT          NOT NULL,
  TEMPLATE_ID  INT,
  CREATED      TIMESTAMP    NOT NULL             DEFAULT CURRENT_TIMESTAMP,
  MODIFIED     TIMESTAMP                         DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tasks_id_primary_key PRIMARY KEY (ID),
  CONSTRAINT tasks_parent_id_foreign_key FOREIGN KEY (PARENT_ID)
  REFERENCES TASKS (ID),
  CONSTRAINT tasks_user_id_foreign_key FOREIGN KEY (USER_ID)
  REFERENCES USERS (ID),
  CONSTRAINT tasks_template_id_foreign_key FOREIGN KEY (TEMPLATE_ID)
  REFERENCES TEMPLATES (ID)
);
